#!/usr/bin/env perl

use strict;
use warnings;

if(@ARGV < 1) {
   usage();
   exit 1;
}


my $password = shift @ARGV;

print '{SHA-512}'.crypt($password,make_salt())."\n";


sub usage {
    print STDERR "Usage:\n";
    print STDERR q{  }.$0." <password>\n";
    print STDERR "Returns a hashed password suitable for Dovecot.\n";
}


sub make_salt {
    our @valid_salt = ( "a".."z", "A".."Z", "0".."9", '/', '+' );
    my $salt = join "", map { $valid_salt[rand(@valid_salt)] } 1..8;
    $salt = '$6$'.$salt;
    return $salt;
}
