#!/usr/bin/env bash

declare LOGSTASH_HOST
declare LOGSTASH_PORT

declare LOG_FILE_PATH
declare LOG_FILE_TYPE

declare LOGSTASH_SSL_CA_URL
declare LOGSTASH_FORWARDER_SKIP_SETUP

if [[ -f /private/logstash-forwarder/vars ]]; then
  source /private/logstash-forwarder/vars
fi

if [[ -f /etc/s6/logstash-forwarder/vars ]]; then
  source /etc/s6/logstash-forwarder/vars
fi

LOGSTASH_HOST=${LOGSTASH_HOST:-}
LOGSTASH_NAME=${LOGSTASH_NAME:-}

LOGSTASH_TCP_PORT=${LOGSTASH_TCP_PORT:-5043}

LOGSTASH_SSL_CA_URL=${LOGSTASH_SSL_CA_URL:-}

if [[ -n ${LOGSTASH_NAME} ]]; then
  LOGSTASH_HOST=logstash
fi

if [[ -n ${LOGSTASH_HOST} ]]; then

  declare have_logstash_ca
  have_logstash_ca=0

  if [[ -f /private/ssl/ca.pem ]]; then
    cp /private/ssl/ca.pem /etc/logstash/ssl/ca.pem
    have_logstash_ca=1
  fi

  if [[ ${have_logstash_ca} -eq 0 ]]; then


    if [[ -n ${LOGSTASH_SSL_CA_URL} ]]; then
      curl -R -L -o /etc/logstash/ssl/ca.pem "${LOGSTASH_SSL_CA_URL}"
    else
      openssl s_client -showcerts -connect "${LOGSTASH_HOST}:${LOGSTASH_TCP_PORT}" </dev/null 2>/dev/null | openssl x509 -outform PEM > /etc/logstash/ssl/ca.pem
    fi
  fi

  if [[ ${LOGSTASH_FORWARDER_SKIP_SETUP} -eq 1 ]]; then
    exit 0;
  fi

  envsubst < /etc/logstash-forwarder.conf.tmpl > /etc/logstash-forwarder.conf

fi
