#!/usr/bin/env bash

declare LOG_FILE_PATH
declare LOG_FILE_TYPE

if [[ -f /private/nginx/vars ]]; then
  source /private/nginx/vars
fi

LOG_FILE_PATH=${LOG_FILE_PATH:-/var/log/nginx/access.log}
LOG_FILE_TYPE=${LOG_FILE_TYPE:-nginx}

echo "LOG_FILE_PATH=${LOG_FILE_PATH}" >> /etc/s6/logstash-forwarder/vars
echo "LOG_FILE_TYPE=${LOG_FILE_TYPE}" >> /etc/s6/logstash-forwarder/vars

rm /etc/s6/logstash-forwarder/down
s6-svc -u /etc/s6/logstash-forwarder
