#!/usr/bin/env bash

sa-update

IMAP_HOST=${IMAP_HOST:-}
IMAP_NAME=${IMAP_NAME:-}

if [[ -n ${IMAP_NAME} ]]; then
    IMAP_HOST=imap
fi

if [[ -z ${IMAP_HOST} ]]; then
    echo "I need either IMAP_HOST set or link to something named imap to connect to!"
    s6-svc -d /etc/s6/spampd
    exit 0
fi

exec spampd --host 0.0.0.0:10025 --relayhost ${IMAP_HOST}:10026 --nodetach --user spampd --group spampd --tagall --config /etc/spampd.conf
