#!/usr/bin/env bash

sa-update

DOVECOT_HOST=${DOVECOT_HOST:-}
DOVECOT_NAME=${DOVECOT_NAME:-}

if [[ -n ${DOVECOT_NAME} ]]; then
    DOVECOT_HOST=dovecot
fi

if [[ -z ${DOVECOT_HOST} ]]; then
    echo "I need either DOVECOT_HOST set or link to something named dovecot to connect to!"
    s6-svc -d /etc/s6/spampd
    exit 0
fi

exec spampd --host 0.0.0.0:10025 --relayhost ${DOVECOT_HOST}:10026 --nodetach --user spampd --group spampd --tagall --config /etc/spampd.conf
